# Generated by Django 5.2 on 2025-04-30 17:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=20)),
                ('lecture_hours', models.IntegerField(default=0)),
                ('tutorial_hours', models.IntegerField(default=0)),
                ('practical_hours', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('employee_id', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tablelogic.department')),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tablelogic.semester')),
            ],
        ),
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tablelogic.section')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usn', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('semester', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8')])),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tablelogic.batch')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tablelogic.section')),
            ],
        ),
        migrations.CreateModel(
            name='PracticalAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_section_wide', models.BooleanField(default=False)),
                ('batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tablelogic.batch')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tablelogic.course')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tablelogic.section')),
                ('teacher1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='practical_teacher1', to='tablelogic.teacher')),
                ('teacher2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='practical_teacher2', to='tablelogic.teacher')),
            ],
        ),
        migrations.CreateModel(
            name='LectureAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tablelogic.course')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tablelogic.section')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tablelogic.teacher')),
            ],
        ),
        migrations.CreateModel(
            name='TutorialAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_section_wide', models.BooleanField(default=False)),
                ('batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tablelogic.batch')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tablelogic.course')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tablelogic.section')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tablelogic.teacher')),
            ],
        ),
        migrations.CreateModel(
            name='TimetableEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(choices=[('mon', 'Monday'), ('tue', 'Tuesday'), ('wed', 'Wednesday'), ('thu', 'Thursday'), ('fri', 'Friday')], max_length=3)),
                ('period', models.IntegerField()),
                ('duration', models.IntegerField(default=1)),
                ('lecture_assignment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tablelogic.lectureassignment')),
                ('practical_assignment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tablelogic.practicalassignment')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tablelogic.room')),
                ('tutorial_assignment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tablelogic.tutorialassignment')),
            ],
        ),
    ]
