# Generated by Django 5.2 on 2025-05-04 12:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tablelogic', '0003_remove_timetableentry_duration_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExtraClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assignment_type', models.CharField(choices=[('lecture', 'Lecture'), ('tutorial', 'Tutorial'), ('practical', 'Practical')], max_length=10)),
                ('assignment_id', models.PositiveIntegerField()),
                ('date', models.DateField()),
                ('period', models.IntegerField()),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tablelogic.room')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tablelogic.teacher')),
            ],
        ),
    ]
