# Generated by Django 5.2 on 2025-05-06 18:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tablelogic', '0004_extraclass'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='extraclass',
            name='assignment_id',
        ),
        migrations.RemoveField(
            model_name='extraclass',
            name='assignment_type',
        ),
        migrations.RemoveField(
            model_name='extraclass',
            name='room',
        ),
        migrations.AddField(
            model_name='extraclass',
            name='batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tablelogic.batch'),
        ),
        migrations.AddField(
            model_name='extraclass',
            name='section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tablelogic.section'),
        ),
    ]
