# Generated by Django 5.2 on 2025-05-06 19:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tablelogic', '0005_remove_extraclass_assignment_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='extraclass',
            name='class_type',
            field=models.CharField(blank=True, choices=[('Lecture', 'Lecture'), ('Tutorial', 'Tutorial'), ('Practical', 'Practical')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='extraclass',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tablelogic.room'),
        ),
        migrations.AlterField(
            model_name='extraclass',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tablelogic.section'),
        ),
    ]
