# Generated by Django 5.2 on 2025-05-06 19:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tablelogic', '0007_alter_extraclass_section'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='extraclass',
            name='class_type',
        ),
        migrations.AlterField(
            model_name='extraclass',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tablelogic.room'),
        ),
    ]
