# Generated by Django 5.2 on 2025-05-07 15:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tablelogic', '0008_remove_extraclass_class_type_alter_extraclass_room'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extraclass',
            name='batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tablelogic.batch'),
        ),
        migrations.AlterField(
            model_name='extraclass',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tablelogic.section'),
        ),
    ]
