# Generated by Django 5.2 on 2025-05-07 17:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tablelogic', '0010_alter_extraclass_batch_alter_extraclass_section'),
    ]

    operations = [
        migrations.AddField(
            model_name='extraclass',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tablelogic.course'),
        ),
    ]
